version: "3.0"
services:
  limesurvey:
    restart: unless-stopped
    build:
      context: 6.0/fpm/
      dockerfile: Dockerfile
    volumes:
      # Hint: This is just an example, change /tmp to something persistent
      - lime_suverys:/var/www/html/upload/surveys
      - lime_html:/var/www/html
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=myuser"
      - "DB_USERNAME=mydb"
      - "DB_NAME=samplepass"
      - "ADMIN_PASSWORD=limeduveryLoginPass"
  lime-web:
    restart: unless-stopped
    image: docker.io/nginx
    links:
      - limesurvey
    ports:
      - "8080:80"
    volumes:
      - ./examples/nginx.conf:/etc/nginx/nginx.conf:ro
      - lime_data:/var/www/html
  lime-db:
    restart: unless-stopped
    image: docker.io/mysql:5.7
    environment:
      - "MYSQL_USER=mysuer"
      - "MYSQL_DATABASE=mydb"
      - "MYSQL_PASSWORD=samplepass"
      - "MYSQL_ROOT_PASSWORD=samplerootPass"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  lime_suverys:
  lime_html:
  mysql_data:
